### PR TITLE
Update esapi.js

### PR DESCRIPTION
**Pull request by SButzbach07**
Added definition for encodeForJS.

### CODE REVIEW

**Comment by jeremiahjstacey** [comment]
@DeadAlready @lirantal  @kwwall @xeno6696 
I'm not overly skilled with javascript, but this is what I would expect this contribution to look like.

Barring objections, I'd like to plan to merge this next weekend (FEB 12 or 13).  Hopefully that leaves enough time to review and voice any concerns.

**Comment by SButzbach07** [comment]
Got it. Thanks for accepting this edit! :)

**Comment by xeno6696** [comment]
This one seems harmless to me.

**Comment by SButzbach07** [comment]
It is better for convenience, not safety, not saying my new addition compromises the security of the file.

**Comment by kwwall** [comment]
The original idea for ESAPI was that the interfaces were supposed to be as
consistent as possible across various programming language implementations
to facilitate knowledge transfer for those who work with ESAPI in different
programming languages. One could argue whether or not this specific Encoder
method/ function should have originally been named 'encodeForJavascript',
'encodeForJavaScript', or 'encodeForJS', but I personally think that making
these different across Javascript vs other programming language
implementations NOW is a step backwards in terms of consistency.

So, I for one think this is the *wrong* decision from that perspective and
instead of doing this, we should submit a PR against the OWASP Cheat Sheet
that got it wrong.

However, I will *not* veto this decision if @xeno6696 and @jeremiahjstacey
wish to accept the PR.

-kevin

**Comment by jeremiahjstacey** [comment]
If that's the intent, then I would agree.  The method `encryptForJS` is not present in the other repositories.

Would you agree it's worth creating a task to remove it from the [root esapi.js file](https://github.com/ESAPI/node-esapi/blob/master/lib/esapi.js)?

```
1081        encodeForJS: this.encodeForJavascript,
```

**Comment by kwwall** [comment]
The question is,  would removing it break anyone's code? If not, yes, it
should be removed and new version published. (I think that is done via "npm
publish", but I don't claim to know all that's involved.) But if it has the
potential to break client code, then  I think we just have to tolerate it.
I 'm guessing that it might,  but you and Matt have examined this more
closely than me.

-kevin

**Comment by jeremiahjstacey** [comment]
My understanding is, from the conversation in #8, that the /lib/esapi.js file is not able to be referenced. That is why we were discussing copying the function to /lib/public/esapi.js, which is accessible.

@xeno6696, does that sound correct? Specifically, that since /lib/esapi.js cannot be referenced by clients there would be no harm in removing the `encodeForJS` function from it?

**Comment by xeno6696** [comment]
I mean, it's not there now, and all it does is wrap the full name encodeForJavascript() call.  I'm not knowledgeable enough about how javascript code ought to be designed and run.  The most I've ever done is fix some minor bugs in code someone else designed.

**Comment by jeremiahjstacey** [comment]
Ok.  At the end of all this I think we are not accepting the change.

This is mostly due to the fact the other forms of ESAPI do not have an equivalent method by this name, and there is a goal to maintain API consistency.

`lib/public/esapi.js` will not have the function `encodeForJS` added.

Although the method does exist in the `lib/esapi.js` file, that file is not published as part of the public package.  Since it is not published, we do not have a need to remove the existing reference of `encodeForJS` from that file.
 
Thank you for bringing this up @SButzbach07, it was a good conversation, and I learned a bit more on the intent of the ESAPI collection.

**Comment by kwwall** [comment]
@SButzbach07 and @jeremiahjstacey - I do think closing this was the correct thing to do. However someone (maybe @SButzbach07  ???) should make a PR to correct the DOM-based XSS cheat sheet. It is in the https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.md file if anyone is interested. If no one wants to do that, let me know and I'll put it on my TODO list.

**Comment by jeremiahjstacey** [comment]
@kwwall I did not see an issue capturing that in the cheatsheet project, so I created one.
https://github.com/OWASP/CheatSheetSeries/issues/847

**Pull request closed without merging**
